### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by muhyj** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#4]
File "TikTok-Views-Follow-Heart-Bot.py", line 1, in <module>
    from selenium import webdriver
ImportError: No module named selenium

im trying to run it on mac
i already have selenium installed?

**Comment by NoNameoN-A** [comment]
Hi you have this error because you must install selenium, but I never used Mac so I can't help you.
But if you go on google and search something like "Install selenium on Mac" you will find a lot results.
I found [it](https://intellipaat.com/community/6064/how-to-install-selenium-webdriver-on-mac-os) but I don't know if work.
Please sell me if you solve (:

**Comment by NoNameoN-A** [comment]
did you solve?
